version: '3'
services:
    backend:
        build: .
        command: bash -c "python3 /code/manage.py migrate && python3 /code/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
